# Session control deploys the student pipelines.

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: academy-session-control
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
    automated:
      prune: false
      selfHeal: false
  source:
    repoURL: https://github.com/lijcam/headsail.git
    path: ./workspace
    targetRevision: HEAD
    helm:
      valueFiles:
        - ../content/sessions/kubernetes-101.yml
      parameters:
        - name: studentCount
          value: "2"
  destination:
    namespace: academy-session-control
    server: https://kubernetes.default.svc