# Fixtures creates the 'fixed' components of a student auxiliary workspace. 
# Including namespace, and rolebased access controls.
#
# We use argo sync-waves to control the deployment order.
# -2 is highest priority, 0 is default priority. 
#
# https://argo-cd.readthedocs.io/en/stable/user-guide/sync-waves/#how-do-i-configure-waves
#

{{- range $i := until (int .Values.studentCount) }}

#
# sync-wave -2  
# 
---
apiVersion: v1
kind: Namespace
metadata:
  name:  auxiliary-student-{{ add1 $i }}
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops

{{- end }}

#
# sync-wave -1
#
---
apiVersion: user.openshift.io/v1
kind: Group
metadata:
  name: cluster-admins
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
users:
  - admin

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: headsail-argo-cluster-role-binding
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    namespace: openshift-gitops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: headsail-student-auxiliary-reader
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
rules:
- apiGroups: [""]
  resources: ["secrets", "configmaps"]
  verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: headsail-student-auxiliary-reader-binding
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
subjects:
{{- range $i := until (int .Values.studentCount) }}
  - kind: ServiceAccount
    name: pipeline
    namespace: auxiliary-student-{{ add1 $i }}
{{- end }}
roleRef:
  kind: Role
  name: headsail-student-auxiliary-reader
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: headsail-cluster-role
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["*"]
- apiGroups: ["tekton.dev"]
  resources: ["clustertasks"]
  verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: headsail-cluster-role-binding
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    namespace: openshift-gitops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: headsail-cluster-role
#
# sync-wave 0 - objects from this point, will deploy with the 
# main application components. See pipelines.yaml
#