{{- $challenges := .Values.challenges -}}
{{- range $i := until (int .Values.studentCount) }}
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: setup
  namespace: auxiliary-student-{{ add1 $i }}
spec:
  tasks:
    - name: seed-student-configuration
      params:
        - name: student-id
          value: "{{ add1 $i }}"
      taskRef:
        kind: ClusterTask
        name: headsail-seed
    - name: provision-student-environment
      params:
        - name: path
          value: {{ first $challenges }}
      runAfter:
        - seed-student-configuration
      taskRef:
        kind: ClusterTask
        name: headsail-student-provision

{{- range $path := $challenges }}
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: challenge-{{ last (splitList "/" $path) }}
  namespace: auxiliary-student-{{ add1 $i }}
spec:
  tasks:
    - name: updating-resources
      params:
        - name: path
          value: {{ $path }}
      taskRef:
        kind: ClusterTask
        name: headsail-student-provision

{{- end }}

---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: session-deploy
  namespace: auxiliary-student-{{ add1 $i }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  pipelineRef:
    name: setup
  serviceAccountName: pipeline
  timeout: 1h0m0s

{{- end }}