---
apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: headsail-student-provision
  labels:
    app.kubernetes.io/version: "0.2"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/categories: Deployment
    tekton.dev/tags: deploy
    tekton.dev/displayName: "argocd"
    tekton.dev/platforms: "linux/amd64"
spec:
  description: >-
    This task syncs student Argo CD applications and waits for it to be healthy.

  params:
    - name: revision
      description: The revision to sync to
      default: HEAD
      type: string
    - name: git-repo
      description:  Repository URL
      default: https://github.com/lijcam/headsail.git
      type: string 
    - name: path
      description: Path in repository to the app directory
      default: content/demo-session/challenges/challenge-1
    - name: argocd-version
      default: "1.8"
      type: string
  stepTemplate:
    envFrom:
      - configMapRef:
          name: headsail-student-configmap
      - configMapRef:
          name: argocd-env-configmap
      - secretRef:
          name: argocd-env-secret
  steps:
    - name: login
      image: registry.redhat.io/openshift-gitops-1/argocd-rhel8:$(params.argocd-version)
      script: |
        #!/usr/bin/env bash
        set -x
        yes | argocd login "$ARGOCD_SERVER" --username="$ARGOCD_USERNAME" --password="$ARGOCD_PASSWORD";

        argocd app delete -l headsail.student-id="$STUDENT_ID" || true
        sleep 5

        argocd app create student-$STUDENT_ID --repo $(params.git-repo) --path $(params.path) --dest-namespace student-$STUDENT_ID --label headsail.student-id=$STUDENT_ID --dest-server https://kubernetes.default.svc --sync-option CreateNamespace=true,ApplyOutOfSyncOnly=true 
        argocd app sync -l headsail.student-id=$STUDENT_ID

        argocd app wait -l headsail.student-id=$STUDENT_ID --health

        argocd logout "$ARGOCD_SERVER"