# quickstart creates the session ConsoleQuickStart. The quickstart provides written instruction to students.

apiVersion: console.openshift.io/v1
kind: ConsoleQuickStart
metadata:
  annotations:
    capability.openshift.io/name: Console
{{- range $index, $path := .Values.challenges }}
  {{- if eq $index 0 }}
    {{- if $.Values.debugMode }}
  name: debug-{{ last (splitList "/" $path) }}
    {{- else }}
  name: {{ last (splitList "/" $path) }}
    {{- end }}
  {{- end }}
{{- end }}
spec:
{{- if .Values.debugMode }}
  displayName: Debug install - {{ .Values.displayName }}
{{- end }}
  description: |-
{{ .Values.description | nindent 4 }}
  durationMinutes: {{ .Values.durationMinutes }}
  introduction: |-
{{ .Values.introduction | nindent 4 }}
  icon: {{ .Values.iconBase64 }}
  tasks:
    {{- range .Values.tasks }}
    - title: {{ .title }}
      description: |-
{{ .description | nindent 8 }}
      review:
        failedTaskHelp: {{ .review.failedTaskHelp }}
        instructions: |-
{{ .review.instructions | nindent 12 }}
      summary:
        failed: {{ .summary.failed }}
        success: {{ .summary.success }}
    {{- end }}